
CXX = g++
CXXFLAGS = -std=c++0x
#CXXFLAGS += -Wall
#CXXFLAGS += -pedantic-errors
#CXXFLAGS += -g
#CXXFLAGS += -O3
#LDFLAGS = -lboost_date_time

OBJS = main.o determinant.o readMatrix.o

SRCS = main.cpp determinant.cpp readMatrix.cpp

HEADERS = determinant.hpp readMatrix.hpp

#target: dependencies
#	rule to build
#

matrix: ${SRCS} ${HEADERS}
	${CXX} ${CXXFLAGS} ${SRCS} -o matrix

#${OBJS}: ${SRCS}
#	${CXX} ${CXXFLAGS} -c $(@:.o=.cpp)
